---
abstract: ' Server Runner For Testing Groonga full-text search engine'
author:
  - 'Okamura. '
build_requires:
  ExtUtils::MakeMaker: 6.42
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 1.00'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Test-Groonga
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  File::Spec: 0
  File::Temp: 0
  File::Which: 0
  Test::TCP: 0
resources:
  license: http://dev.perl.org/licenses/
  repository: git://github.com/okamuuu/Test-Groonga.git
version: 0.03
